### ISSUE TITLE
Dart language support

### ISSUE THREAD

**Issue by d3xt3r2909** [codersrank-org/repo_info_extractor#56]
Is it possible for you to add support for dart language (Flutter). I am currently trying to get stats from your scripts and it is finishing without any errors. But, the thing is that I cannot find "repo_data.json.zip" file. 

OS: Windows. 

After this command: python src\main.py path\to\repo 
I am getting this message: 
`(base) C:\Users\nihad\AndroidStudioProjects\repo_info\repo_info_extractor>python src\main.py C:\Users\nihad\AndroidStudioProjects\flutter\PROJECT_NAME
Analyzing repo under C:\Users\nihad\AndroidStudioProjects\flutter\PROJECT_NAME...
[============================================================] 100.0% ...Analyzing commits
? The following contributors were found in the repository.             Select which ones you are. (With SPACE you can select more than one)  [Nihad Delic -> EMAIL]
[29/10/2019 11:36:40] Filtering commits by emails . ['EMAIL']
[29/10/2019 11:36:40] Copying the repository to a temporary location, this can take a while...
[29/10/2019 11:36:58] Finished copying the repository`

But I need to tell you also, great job guys

**Comment by peti2001** [comment]
Hi @d3xt3r2909,

I have added the Dart support. Please pull the latest updates and run the script again. 

Best,
Peter

**Comment by d3xt3r2909** [comment]
Hi @peti2001, 

First of all thank you for quick response and solution. 

I have now another issue with permissions. (I am not sure is this issue related also with this topic, so if it is not, I will create separated issues.) 

After command 

`python src\main.py path\to\repo`

1. Analyzing repo under is success 
2. I have choose which commits to filter by email
3. Copying the repository to a temporary location - finished
4. Analyzing libraries - ERROR with permission error [WinError 5] (I have started CMD with administrator account)

Here is error message: 

`[============================================================] 100.0% ...Analyzing libraries
[31/10/2019 13:27:10] Deleting C:\Users\nihad\AppData\Local\Temp\8e54512e-aada-45e9-b953-efffbcf08805
Traceback (most recent call last):
  File "src\main.py", line 46, in <module>
    main()
  File "src\main.py", line 37, in main
    initialize(args.directory, args.skip_obfuscation, args.output, args.parse_libraries, args.email, args.skip_upload)
  File "C:\Users\nihad\AndroidStudioProjects\new_info\repo_info_extractor\src\init.py", line 70, in initialize
    libs = al.get_libraries()
  File "C:\Users\nihad\AndroidStudioProjects\new_info\repo_info_extractor\src\analyze_libraries.py", line 83, in get_libraries
    _cleanup(tmp_repo_path)
  File "C:\Users\nihad\AndroidStudioProjects\new_info\repo_info_extractor\src\analyze_libraries.py", line 88, in _cleanup
    shutil.rmtree(tmp_repo_path)
  File "C:\Users\nihad\Anaconda3\lib\shutil.py", line 516, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\nihad\Anaconda3\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\nihad\Anaconda3\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\nihad\Anaconda3\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\nihad\Anaconda3\lib\shutil.py", line 400, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\nihad\Anaconda3\lib\shutil.py", line 398, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\nihad\\AppData\\Local\\Temp\\8e54512e-aada-45e9-b953-efffbcf08805\\.git\\objects\\00\\f6e7b062ab6f02322d6ade534f4ad7c90f97c4'`

**Comment by d3xt3r2909** [comment]
I have fix this issue (changing PC LoL). Thanks for help
