### ISSUE TITLE
Cannot extract data from microsoft/vscode

### ISSUE THREAD

**Issue by peti2001** [codersrank-org/repo_info_extractor#6]
When you try to calculate the private repo zip from https://github.com/c the script dies with an error:
```
Traceback (most recent call last):
  File "src/main.py", line 20, in <module>
    ar.create_commits_entity_from_branch(branch.name)
  File "[...]/repo_info_extractor/src/analyze_repo.py", line 34, in create_commits_entity_from_branch
    self.commit_list[commit.hexsha] = Commit(commit.author.name, commit.author.email, commit.committed_datetime, commit.hexsha, commit.parents, branch, self.skip_obfuscation)
  File "[...]/repo_info_extractor/src/entity/commit.py", line 91, in _init_
    self.obfuscate()
  File "[...]/repo_info_extractor/src/entity/commit.py", line 103, in obfuscate
    md5_hash.update(self.author_email.encode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'encode'
```

It is happening if there is a commit with an author who has no email or name.

**Comment by peti2001** [comment]
Fixed
