### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by johanguse** [codersrank-org/repo_info_extractor#61]
I try to analyse a repo, but I get error.
I try with 2 different folder.

I use: python src\main.py C:\Users\Johan\Desktop\TEMP\repos\app-master

`
Traceback (most recent call last):
  File "src\main.py", line 2, in <module>
    from init import initialize
  File "C:\Users\Johan\Desktop\TEMP\codersrank\src\init.py", line 6, in <module>
    from analyze_libraries import AnalyzeLibraries
  File "C:\Users\Johan\Desktop\TEMP\codersrank\src\analyze_libraries.py", line 101
    print(timed_message, *argv)
                         ^
SyntaxError: invalid syntax
`

**Comment by andremilke** [comment]
I have the same issue: 
 Search repos on ../repos/, 1 folders deep
Found 1 repos under ../repos/

Traceback (most recent call last):
  File "src/main.py", line 2, in <module>
    from init import initialize
  File "/home/amsantos/repo_info_extractor/src/init.py", line 6, in <module>
    from analyze_libraries import AnalyzeLibraries
  File "/home/amsantos/repo_info_extractor/src/analyze_libraries.py", line 101
    print(timed_message, *argv)
                         ^
SyntaxError: invalid syntax
Finished

**Comment by Pratik948** [comment]
Getting exact issue on macOS Catalina 10.15.1

**Comment by GigaMick** [comment]
Same issue here - mac os catalina 10.15

**Comment by gedas93** [comment]
Same issue on Elementary OS 5.0 Juno

**Comment by jrmypttrsn** [comment]
Same issue, macOS 10.15.1.

**Comment by rabxly** [comment]
The issue is caused by running the script on Python2. We only support Python3 now. Please check your version with
```
python -V
```

**Comment by johanguse** [comment]
With Python 3.7.5 - Windows 10

`Traceback (most recent call last):
  File "C:\Users\Johan\Desktop\TEMP\repos\repo_info_extractor\src\main.py", line 58, in <module>       
    main()
  File "C:\Users\Johan\Desktop\TEMP\repos\repo_info_extractor\src\main.py", line 48, in main
    args.commit_size_limit, args.file_size_limit)
  File "C:\Users\Johan\Desktop\TEMP\repos\repo_info_extractor\src\init.py", line 29, in initialize     
    repo = git.Repo(directory)
  File "C:\Users\Johan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\git\repo\base.py", line 168, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: C:\Users\Johan\Desktop\TEMP\repos\app-master`

**Comment by abduraufsherkulov** [comment]
You guys probably using git bash or Powershell or other terminal on windows. Try using cmd and follow given steps for windows: 

```
git clone https://github.com/codersrankOrg/repo_info_extractor.git
cd repo_info_extractor
install.bat
python src\main.py path\to\repo
dir
```
worked like a charm for me.

**Comment by varora1406** [comment]
Same issue here

E:\repos\repo_info_extractor>python src\main.py _repo_complete_path_
Traceback (most recent call last):
  File "src\main.py", line 2, in <module>
    from init import initialize
  File "E:\repos\repo_info_extractor\src\init.py", line 7, in <module>
    from analyze_libraries import AnalyzeLibraries
  File "E:\repos\repo_info_extractor\src\analyze_libraries.py", line 204
    print(timed_message, *argv)
                         ^
SyntaxError: invalid syntax

**Comment by errorsolve** [comment]
All Possible Solution Added at Here [SyntaxError: invalid syntax to repo init in the AOSP code in Python](https://exerror.com/syntaxerror-invalid-syntax-to-repo-init-in-the-aosp-code-in-python/)

**Comment by exeptionerror** [comment]
[Here Is All Possible Solution added at one place SyntaxError: invalid syntax to repo init in the AOSP code](https://exerror.com/syntaxerror-invalid-syntax-to-repo-init-in-the-aosp-code/)

**Comment by peti2001** [comment]
We released a new version of the `repo_info_extractor`. This is not relevant anymore.
