### ISSUE TITLE
ModuleNotFoundError: No module named 'gitdb.utils.compat'

### ISSUE THREAD

**Issue by miki995** [codersrank-org/repo_info_extractor#85]
When I run ./run-docker.sh pathToRepo I get this error:

```
Traceback (most recent call last):
  File "src/main.py", line 2, in <module>
    from init import initialize
  File "/app/src/init.py", line 2, in <module>
    import git
  File "/opt/venv/lib/python3.7/site-packages/git/__init__.py", line 38, in <module>
    from git.exc import *                       # @NoMove @IgnorePep8
  File "/opt/venv/lib/python3.7/site-packages/git/exc.py", line 9, in <module>
    from git.compat import UnicodeMixin, safe_decode, string_types
  File "/opt/venv/lib/python3.7/site-packages/git/compat.py", line 16, in <module>
    from gitdb.utils.compat import (
ModuleNotFoundError: No module named 'gitdb.utils.compat'
Finished

```

**Comment by Harmon758** [comment]
See https://github.com/gitpython-developers/GitPython/issues/983.

**Comment by miki995** [comment]
So, we have to add this line `gitdb2==3.0.1` to requirements.txt to be able to run run.sh and how is that docker image doesn't have that?

@peti2001 @vhraban @rabxly @crhraban @shank318 
Guys can you have a look at it?

**Comment by peti2001** [comment]
We released a new version of the `repo_info_extractor`. This is not relevant anymore.
